# Generated by Django 5.2.4 on 2025-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered'), ('New', 'New')], default=True, max_length=10),
        ),
    ]
