# Generated by Django 5.2.4 on 2025-08-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered'), ('Completed', 'Completed')], default=True, max_length=10),
        ),
    ]
